server:
  port: 8761

spring:
  application:
    name: discovery-service
  
  # Disable security for this demo
  security:
    basic:
      enabled: false

# Eureka configuration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
